title = "Iman Shames Homepage"
languageCode = "en-us"
baseURL = "https://eemensch.github.io/"
# baseURL = "http://localhost:1313/"
# copyright = "Sample custom notice © {year}"
theme = "hugo-flex"


[pagination]
pagerSize = 10

[taxonomies]
tags = "tags"
categories = "categories"


[params]
  #showMenuItems = true
  favicon = "/static/xterm.png"
  #showBreadCrumbs = true
  noClasses = false                                     # Set to true to use inline CSS for syntax highlighting
  katex = "0.16.22"                                     # KaTeX version / leave empty to use the latest version
  toc = true


# Navigation
[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    title = "Home"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "news"
    name = "news"
    title = "News"
    url = "/news"
    weight = 2
  
  [[menu.main]]
    identifier = "research"
    name = "research"
    title = "Research"
    url = "/research"
    weight = 3
  
  [[menu.main]]
    identifier = "teaching"
    name = "teaching"
    title = "Teaching"
    url = "/teaching"
    weight = 4

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

  [markup.highlight]
      noClasses = false
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\\[', '\\]'], ['$$', '$$']]
inline = [['\\(', '\\)']]


